name: Profiling Apache.JMeter with various tools

on: [push]

jobs:
  job_1:
    name: Simple run Apache.JMeter
steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 11 for x64
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
      architecture: x64
      cache: maven
  - name: Run the Maven verify phase
    run: mvn --batch-mode --update-snapshots verify
  - run: mkdir staging && cp target/*.jar staging
  - uses: actions/upload-artifact@v2
    with:
      name: Package
      path: stagings